theme: jekyll-theme-minimal
title: [ThamizhiLIP v0.11]
description: [ThamizhiLIP: Thamizhi Linguistic Information Processing Library]
logo: [https://raw.githubusercontent.com/sarves/thamizhilip/main/logo.png]
show_downloads: ["true"]
